FROM node:8.11.1-alpine

RUN mkdir -p /usr/src/ias-display/node_modules
RUN chown -R node:node /usr/src/ias-display
RUN chown -R node:node /usr/src/ias-display/node_modules
WORKDIR /usr/src/ias-display

USER node
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH="/home/node/.npm-global/bin:${PATH}"
RUN npm install -g @angular/cli@1.6.5

USER root

EXPOSE 4200
VOLUME /usr/src/ias-display
