/** Set of mock Alarms for the tests */
export const MockAlarms = [
  {
    'value': 4,
    'core_id': 'critical',
    'running_id': 'critical',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 4],
  },
  {
    'value': 3,
    'core_id': 'high',
    'running_id': 'high',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 3],
  },
  {
    'value': 2,
    'core_id': 'medium',
    'running_id': 'medium',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 2],
  },
  {
    'value': 1,
    'core_id': 'low',
    'running_id': 'low',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 1],
  },
  {
    'value': 0,
    'core_id': 'clear',
    'running_id': 'clear',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 0],
  },
  {
    'value': 0,
    'core_id': 'unknown',
    'running_id': 'unknown',
    'mode': 7,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 0],
  },
  {
    'value': 0,
    'core_id': 'maintenance',
    'running_id': 'maintenance',
    'mode': 4,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 0],
  },
  {
    'value': 0,
    'core_id': 'shutteddown',
    'running_id': 'shutteddown',
    'mode': 3,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 0],
  },
  {
    'value': 0,
    'core_id': 'malfunctioning',
    'running_id': 'malfunctioning',
    'mode': 8,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 0],
  },
  {
    'value': 4,
    'core_id': 'critical_unreliable',
    'running_id': 'critical_unreliable',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 4],
  },
  {
    'value': 3,
    'core_id': 'high_unreliable',
    'running_id': 'high_unreliable',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 3],
  },
  {
    'value': 2,
    'core_id': 'medium_unreliable',
    'running_id': 'medium_unreliable',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 2],
  },
  {
    'value': 1,
    'core_id': 'low_unreliable',
    'running_id': 'low_unreliable',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 1],
  },
  {
    'value': 0,
    'core_id': 'clear_unreliable',
    'running_id': 'clear_unreliable',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 0],
  },
  {
    'value': 0,
    'core_id': 'unknown_unreliable',
    'running_id': 'unknown_unreliable',
    'mode': 7,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 0],
  },
  {
    'value': 0,
    'core_id': 'maintenance_unreliable',
    'running_id': 'maintenance_unreliable',
    'mode': 4,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 0],
  },
  {
    'value': 0,
    'core_id': 'shutteddown_unreliable',
    'running_id': 'shutteddown_unreliable',
    'mode': 3,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 0],
  },
  {
    'value': 0,
    'core_id': 'malfunctioning_unreliable',
    'running_id': 'malfunctioning_unreliable',
    'mode': 8,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 0],
  }
];
