import { Alarm } from '../../data/alarm';

/** Set of mock Alarms for the tests */
export const MockAlarms = [
  Alarm.asAlarm({
    'value': 0,
    'core_id': 'clear',
    'running_id': 'clear',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 0],
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  }),
  Alarm.asAlarm({
    'value': 1,
    'core_id': 'low',
    'running_id': 'low',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 1],
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  }),
  Alarm.asAlarm({
    'value': 2,
    'core_id': 'medium',
    'running_id': 'medium',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 2],
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  }),
  Alarm.asAlarm({
    'value': 3,
    'core_id': 'high',
    'running_id': 'high',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 3],
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  }),
  Alarm.asAlarm({
    'value': 4,
    'core_id': 'critical',
    'running_id': 'critical',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'value_change_timestamp': 1267252440000,
    'value_change_transition': [0, 4],
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  }),
];
