export enum OperationalMode {
  startup = 0,
  initialization = 1,
  closing = 2,
  shuttedown = 3,
  maintenance = 4,
  operational = 5,
  degraded = 6,
  unknown = 7,
};

/**
* Class to define Alarm objects
*/
export class Alarm {
  /** Primary key */
  pk: number;

  /**
  * Value that represents the state of the {@link Alarm}.
  * Can be either 0 (CLEARED) or 1 (SET)
  */
  value: number;

  /** Id used to identify the {@link Alarm} in the IAS Core */
  core_id: string;

  /** Id used to identify the {@link Alarm} and its parents in the IAS Core */
  running_id: string;

  /** Operational mode of the {@link Alarm} */
  mode: OperationalMode;

  /** Timestamp at which the {@link Alarm} was generated by the IAS Core */
  core_timestamp: number;

  /**
  * The "constructor"
  *
  * @param {Object} attributes a dictionary containing the attributes to
  * create the object
  */
  constructor(attributes: Object = {}){
    Object.assign(this, attributes)
  }

  /**
  * Class method that checks if an object corresponds to an Alarm object
  *
  * @param {any} json the object to check
  * @returns {boolean} true if it is an {@link Alarm}, false if not
  */
  static isValidAlarm(json: any): boolean {
    return (
      json.hasOwnProperty("value") &&
      json.hasOwnProperty("core_id") &&
      json.hasOwnProperty("running_id") &&
      json.hasOwnProperty("mode") &&
      json.hasOwnProperty("core_timestamp")
    );
  }

  /**
  * Class method that receives an object and returns copy as an {@link Alarm}
  *
  * @param {any} json the object to convert to an Alarm
  * @param {number} pk the primary key of the Alarm in the database
  */
  static asAlarm(json: any, pk: number): Alarm {
    if (!this.isValidAlarm(json)) {
      return null;
    }
    let value = <string>json['value'];
    let core_id = <string>json['core_id'];
    let running_id = <string>json['running_id'];
    let mode = <number>json['mode'];
    let core_timestamp = <number>json['core_timestamp'];
    return new Alarm({ pk, value, core_id, running_id, mode, core_timestamp });
  }

  /**
  * Returns a string representation of the {@link Alarm.mode} attribute
  *
  * @returns {string} a string representation of the operational mode of the Alarm
  */
  getModeAsString(): string {
    return OperationalMode[this.mode];
  }

  /**
  * Returns a string representation of the {@link Alarm.value} attribute
  *
  * @returns {string} a string representation of the value of the Alarm
  */
  getValueAsString(): string {
    if (this.value == 0){
      return 'Cleared';
    }
    else {
      return 'Set';
    }
  }
}
