import { AlarmImageSet } from '../alarm/alarm.component';

/** Set of mock Alarms for the tests */
export const MockAlarms = [
  {
    'value': 4,
    'core_id': 'critical',
    'running_id': 'critical',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 3,
    'core_id': 'high',
    'running_id': 'high',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 2,
    'core_id': 'medium',
    'running_id': 'medium',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 1,
    'core_id': 'low',
    'running_id': 'low',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 0,
    'core_id': 'clear',
    'running_id': 'clear',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 1,
    'core_id': 'unknown_low',
    'running_id': 'unknown_low',
    'mode': 7,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 0,
    'core_id': 'unknown_clear',
    'running_id': 'unknown_clear',
    'mode': 7,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 1,
    'core_id': 'maintenance_low',
    'running_id': 'maintenance_low',
    'mode': 4,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 0,
    'core_id': 'maintenance_clear',
    'running_id': 'maintenance_clear',
    'mode': 4,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 1,
    'core_id': 'shutteddown_low',
    'running_id': 'shutteddown_low',
    'mode': 3,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 0,
    'core_id': 'shutteddown_clear',
    'running_id': 'shutteddown_clear',
    'mode': 3,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 1,
    'core_id': 'malfunctioning_low',
    'running_id': 'malfunctioning_low',
    'mode': 8,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 0,
    'core_id': 'malfunctioning_clear',
    'running_id': 'malfunctioning_clear',
    'mode': 8,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 4,
    'core_id': 'critical_unreliable',
    'running_id': 'critical_unreliable',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 3,
    'core_id': 'high_unreliable',
    'running_id': 'high_unreliable',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 2,
    'core_id': 'medium_unreliable',
    'running_id': 'medium_unreliable',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 1,
    'core_id': 'low_unreliable',
    'running_id': 'low_unreliable',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 0,
    'core_id': 'clear_unreliable',
    'running_id': 'clear_unreliable',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 1,
    'core_id': 'unknown_low_unreliable',
    'running_id': 'unknown_low_unreliable',
    'mode': 7,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 0,
    'core_id': 'unknown_clear_unreliable',
    'running_id': 'unknown_clear_unreliable',
    'mode': 7,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 1,
    'core_id': 'maintenance_low_unreliable',
    'running_id': 'maintenance_low_unreliable',
    'mode': 4,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 0,
    'core_id': 'maintenance_clear_unreliable',
    'running_id': 'maintenance_clear_unreliable',
    'mode': 4,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 1,
    'core_id': 'shutteddown_low_unreliable',
    'running_id': 'shutteddown_low_unreliable',
    'mode': 3,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 0,
    'core_id': 'shutteddown_clear_unreliable',
    'running_id': 'shutteddown_clear_unreliable',
    'mode': 3,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 1,
    'core_id': 'malfunctioning_low_unreliable',
    'running_id': 'malfunctioning_low_unreliable',
    'mode': 8,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 0,
    'core_id': 'malfunctioning_clear_unreliable',
    'running_id': 'malfunctioning_clear_unreliable',
    'mode': 8,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': false,
    'dependencies': [],
  },
  {
    'value': 1,
    'core_id': 'shelved',
    'running_id': 'shelved',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 1,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': true,
    'dependencies': [],
  },
  {
    'value': 1,
    'core_id': 'shelved_unreliable',
    'running_id': 'shelved_unreliable',
    'mode': 5,
    'core_timestamp': 1267252440000,
    'state_change_timestamp': 1267252440000,
    'validity': 0,
    'description': 'my description',
    'url': 'https://www.alma.cl',
    'sound': 'sound1',
    'can_shelve': true,
    'ack': false,
    'shelved': true,
    'dependencies': [],
  }
];
